name: 'TFLint'
description: 'Runs tflint, Terraform Linter'

inputs:
  files:
    description: 'List of files to lint'
    required: true

runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/exec/wrapper-tflint.sh '${{ inputs.files }}' "$GITHUB_ACTION_PATH/exec/tflint.hcl"
      shell: bash
